// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/novel_crawler/internal/data/ent/novelclue"
	"github.com/novel_crawler/internal/data/ent/predicate"
)

// NovelClueDelete is the builder for deleting a NovelClue entity.
type NovelClueDelete struct {
	config
	hooks    []Hook
	mutation *NovelClueMutation
}

// Where appends a list predicates to the NovelClueDelete builder.
func (ncd *NovelClueDelete) Where(ps ...predicate.NovelClue) *NovelClueDelete {
	ncd.mutation.Where(ps...)
	return ncd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ncd *NovelClueDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ncd.hooks) == 0 {
		affected, err = ncd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NovelClueMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ncd.mutation = mutation
			affected, err = ncd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ncd.hooks) - 1; i >= 0; i-- {
			if ncd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ncd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ncd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncd *NovelClueDelete) ExecX(ctx context.Context) int {
	n, err := ncd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ncd *NovelClueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: novelclue.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: novelclue.FieldID,
			},
		},
	}
	if ps := ncd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ncd.driver, _spec)
}

// NovelClueDeleteOne is the builder for deleting a single NovelClue entity.
type NovelClueDeleteOne struct {
	ncd *NovelClueDelete
}

// Exec executes the deletion query.
func (ncdo *NovelClueDeleteOne) Exec(ctx context.Context) error {
	n, err := ncdo.ncd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{novelclue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ncdo *NovelClueDeleteOne) ExecX(ctx context.Context) {
	ncdo.ncd.ExecX(ctx)
}
