// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/novel_crawler/internal/data/ent/novel"
	"github.com/novel_crawler/internal/data/ent/novelclue"
	"github.com/novel_crawler/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	novelMixin := schema.Novel{}.Mixin()
	novelMixinFields0 := novelMixin[0].Fields()
	_ = novelMixinFields0
	novelFields := schema.Novel{}.Fields()
	_ = novelFields
	// novelDescCreateTime is the schema descriptor for create_time field.
	novelDescCreateTime := novelMixinFields0[0].Descriptor()
	// novel.DefaultCreateTime holds the default value on creation for the create_time field.
	novel.DefaultCreateTime = novelDescCreateTime.Default.(func() time.Time)
	// novelDescUpdateTime is the schema descriptor for update_time field.
	novelDescUpdateTime := novelMixinFields0[1].Descriptor()
	// novel.DefaultUpdateTime holds the default value on creation for the update_time field.
	novel.DefaultUpdateTime = novelDescUpdateTime.Default.(func() time.Time)
	// novel.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	novel.UpdateDefaultUpdateTime = novelDescUpdateTime.UpdateDefault.(func() time.Time)
	novelclueMixin := schema.NovelClue{}.Mixin()
	novelclueMixinFields0 := novelclueMixin[0].Fields()
	_ = novelclueMixinFields0
	novelclueFields := schema.NovelClue{}.Fields()
	_ = novelclueFields
	// novelclueDescCreateTime is the schema descriptor for create_time field.
	novelclueDescCreateTime := novelclueMixinFields0[0].Descriptor()
	// novelclue.DefaultCreateTime holds the default value on creation for the create_time field.
	novelclue.DefaultCreateTime = novelclueDescCreateTime.Default.(func() time.Time)
	// novelclueDescUpdateTime is the schema descriptor for update_time field.
	novelclueDescUpdateTime := novelclueMixinFields0[1].Descriptor()
	// novelclue.DefaultUpdateTime holds the default value on creation for the update_time field.
	novelclue.DefaultUpdateTime = novelclueDescUpdateTime.Default.(func() time.Time)
	// novelclue.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	novelclue.UpdateDefaultUpdateTime = novelclueDescUpdateTime.UpdateDefault.(func() time.Time)
}
