// Code generated by entc, DO NOT EDIT.

package novelclue

import (
	"time"
)

const (
	// Label holds the string label denoting the novelclue type in the database.
	Label = "novel_clue"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldCategoryTitle holds the string denoting the category_title field in the database.
	FieldCategoryTitle = "category_title"
	// FieldIntro holds the string denoting the intro field in the database.
	FieldIntro = "intro"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// Table holds the table name of the novelclue in the database.
	Table = "novel_clues"
)

// Columns holds all SQL columns for novelclue fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTitle,
	FieldDate,
	FieldScore,
	FieldAuthor,
	FieldCategoryTitle,
	FieldIntro,
	FieldLink,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)
