// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Novel is the predicate function for novel builders.
type Novel func(*sql.Selector)

// NovelClue is the predicate function for novelclue builders.
type NovelClue func(*sql.Selector)
